/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summitscheduleria;

/**
 *
 * @author alexelevathingal
 */
public class welcomescreenpanel extends javax.swing.JPanel {
mainscreen m;  

   
    public welcomescreenpanel() {
        initComponents();
    }
    
     public void setFrame(mainscreen f){ //setFrame() method updates the look of the mainscreen everytime an action is performed
        m= f;
    }   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        intropanel = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        newuser = new javax.swing.JButton();
        existinguser = new javax.swing.JButton();

        intropanel.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 24)); // NOI18N
        intropanel.setForeground(new java.awt.Color(51, 153, 0));
        intropanel.setText("Welcome to the Summit Scheduler!");

        instructions.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 13)); // NOI18N
        instructions.setText("Are you a new or existing user?");

        newuser.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 24)); // NOI18N
        newuser.setText("New");
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });
        newuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserActionPerformed(evt);
            }
        });

        existinguser.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 24)); // NOI18N
        existinguser.setText("Existing");
        existinguser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existinguserMouseClicked(evt);
            }
        });
        existinguser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existinguserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(intropanel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instructions)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(existinguser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(intropanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newuser)
                .addGap(12, 12, 12)
                .addComponent(existinguser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserActionPerformed

    }//GEN-LAST:event_newuserActionPerformed

    private void existinguserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existinguserActionPerformed

    }//GEN-LAST:event_existinguserActionPerformed

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        accountcreatorpanel a = new accountcreatorpanel();
        a.setFrame(m);
        m.add(a);
        a.setVisible(true);
        a.setLocation(0,0);
        a.setSize(400,330);
        m.setSize(450,380);
        this.setVisible(false);
    }//GEN-LAST:event_newuserMouseClicked
//these buttons will direct the user to one panel or another
    private void existinguserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existinguserMouseClicked
        loginscreenpanel a = new loginscreenpanel();
        a.setFrame(m);
        m.add(a);
        a.setVisible(true);
        a.setLocation(20,0);
        a.setSize(364,209);
        m.setSize(400,250);
        this.setVisible(false);
    }//GEN-LAST:event_existinguserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton existinguser;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel intropanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newuser;
    // End of variables declaration//GEN-END:variables
}
